/*
 *
 * Organize constants
 *
 */
export const ActionTypes = {
  GET_GROUPS: 'app/Organize/GET_GROUPS',
  GET_GROUPS_SUCCESS: 'app/Organize/GET_GROUPS_SUCCESS',
  GET_GROUPS_END: 'app/Organize/GET_GROUPS_END',
  GET_GROUPS_ERROR: 'app/Organize/GET_GROUPS_ERROR',

  GET_GROUP: 'app/Organize/GET_GROUP',
  GET_GROUP_SUCCESS: 'app/Organize/GET_GROUP_SUCCESS',
  GET_GROUP_END: 'app/Organize/GET_GROUP_END',
  GET_REBELS_BY_GROUP: 'app/Organize/GET_REBELS_BY_GROUP',
  GET_REBELS_BY_GROUP_SUCCESS: 'app/Organize/GET_REBELS_BY_GROUP_SUCCESS',
  GET_REBELS_BY_GROUP_END: 'app/Organize/GET_REBELS_BY_GROUP_END',
  CLEAR_SELECTED_GROUP: 'app/Organize/CLEAR_SELECTED_GROUP',
  CHANGE_STAFF: 'app/Organize/CHANGE_STAFF',
  CHANGE_PLATOON_OFFICER: 'app/Organize/CHANGE_PLATOON_OFFICER',
  CHANGE_PLATOON_SQUAD_OFFICER: 'app/Organize/CHANGE_PLATOON_SQUAD_OFFICER',
  CHANGE_PLATOON_SQUAD_TEAM_OFFICER:
    'app/Organize/CHANGE_PLATOON_SQUAD_TEAM_OFFICER',
  CHANGE_PLATOON_SQUAD_TEAM_MEMBER:
    'app/Organize/CHANGE_PLATOON_SQUAD_TEAM_MEMBER',
  CHANGE_SQUAD_OFFICER: 'app/Organize/CHANGE_SQUAD_OFFICER',
  CHANGE_SQUAD_TEAM_OFFICER: 'app/Organize/CHANGE_SQUAD_TEAM_OFFICER',
  CHANGE_SQUAD_TEAM_MEMBER: 'app/Organize/CHANGE_SQUAD_TEAM_MEMBER',
  SAVE_FORM: 'app/Organize/SAVE_FORM',
  SAVE_FORM_SUCCESS: 'app/Organize/SAVE_FORM_SUCCESS',
  SAVE_FORM_END: 'app/Organize/SAVE_FORM_END',
  SAVE_FORM_ERROR: 'app/Organize/SAVE_FORM_ERROR',
  CLEAR_FORM: 'app/Organize/CLEAR_FORM',
};
